@startuml sys_arch

package "Блокчейн Layer" {
    [Умные контракты] as SC
    [RPC-узел] as RPC
}

package "Система" {
    frame "Telegram-бот" {
        [Регистрация пользователя]
        [Запрос на выпуск диплома]
        [Запрос на верификацию диплома]
    }
    frame "Функции умного контракта" {
        [Создание коллекции]
        [Выпуск диплома]
        [Верификация диплома]
        [Управление мультиподписью]
    }
    frame "Защита данных" {
        [Преобразование информации]
        [Минимизация информации]
    }
}

package "Пользовательский кошелёк" {
    [Кастодиальный кошелёк]
    [Некастодиальный кошелёк]
    [Интеграция с Thirdweb]
}

database "Блокчейн" {
    [Коллекции дипломов]
    [Выпущенные дипломы]
}

[Регистрация пользователя] --> [Создание коллекции]
[Регистрация пользователя] --> [Интеграция с Thirdweb]
[Запрос на выпуск диплома] --> [Выпуск диплома]
[Запрос на выпуск диплома] --> [Управление мультиподписью]
[Запрос на верификацию диплома] --> [Верификация диплома]

[Создание коллекции] --> SC
[Выпуск диплома] --> SC
[Верификация диплома] --> SC
[Управление мультиподписью] --> SC

[Преобразование информации] --> [Выпуск диплома]
[Минимизация информации] --> [Выпуск диплома]

SC --> RPC
RPC --> [Блокчейн]

[Блокчейн] --> [Коллекции дипломов]
[Блокчейн] --> [Выпущенные дипломы]

[Кастодиальный кошелёк] .down.> [Интеграция с Thirdweb]
[Некастодиальный кошелёк] .down.> [Интеграция с Thirdweb]
[Интеграция с Thirdweb] --> [Регистрация пользователя]

@enduml
