@startuml data_proc

actor "Пользователь" as User
participant "Интерфейс системы" as Interface
participant "Сервер приложений" as Server
participant "Модуль хеширования" as HashModule
database "Временная БД" as DB
database "IPFS" as IPFS
participant "Блокчейн" as Blockchain

User -> Interface: Предоставление CODE и ФИО
Interface -> Server: Передача данных
Server -> HashModule: Подготовка данных для хеширования
HashModule -> HashModule: Хеширование данных
HashModule -> DB: Копия данных
DB -> IPFS: Загрузка данных
IPFS -> Blockchain: Загрузка метаданных
Blockchain -> Server: Подтверждает успешное хранение данных
Server -> Interface: Подтверждение пользователю
Interface -> User: Статус верификации данных

@enduml