@startuml diploma_issue

actor "Администратор (Университет)" as Admin
actor "Студент" as Student
actor "Комиссия" as Committee
entity "Telegram-бот" as Bot
entity "Смарт-контракты" as Contracts
database "IPFS" as IPFS
database "Блокчейн" as Blockchain
entity "Личный кошелек" as Wallet

Admin -> Contracts: Создание коллекции\nУстановка HMAC
Admin -> Contracts: Настройка мультиподписи\nУказание числа и состава подписей
Student -> Bot: Переход по deeplink
Bot -> Contracts: Запрос на выпуск\n(Код из deeplink)
Contracts -> IPFS: Загрузка изображения
Contracts -> Committee: Запрос на подпись
Committee -> Contracts: Подписание диплома
Contracts -> IPFS: Загрузка метаданных
Contracts -> IPFS: Чеканка токена
IPFS -> Wallet: Передача диплома
Wallet -> Blockchain: Регистрация диплома\n(+Верификация)

@enduml
